apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: python-hlypsghz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-hlypsghz 
  name: python-hlypsghz
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: python-hlypsghz
    weight: 100 
